[preprocessor.mermaid]
command = "mdbook-mermaid"

[book]
authors = ["dxo", "msoos"]
language = "en"
multilingual = false
src = "src"
title = "hevm"


[output.html]
no-section-label = true
additional-js = ["solidity.min.js", "mermaid.min.js", "mermaid-init.js"]
additional-css = ["book.css"]
git-repository-url = "https://github.com/argotorg/hevm"
edit-url-template = "hhttps://github.com/argotorg/hevm/edit/main/{path}"

git-repository-icon = "fa-github"

[output.html.fold]
enable = true
